# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8c808b6d0253546daa061b9c6234579807d21d4fe649dc02b2387a1be476f36cb85f6837a89a3cfe555cf15ebda8f5596425a9dbb9068364daa75ebb68ec9a

test:
  secret_key_base: bf0e3e9adb9f884e75132fda70d82a8ee78f654e18813b4ea8c71fa0f611e7dbb8ff38964c69895f08e62c52afe6733a1c49977f979ba602ac32652a8ece4f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
