# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf6a3abf18009b036db8a8270f971afae0b8912cfdafc7e7aa965865c5b830aab528590c9b9912feb6085ca15bdf509bd7ecdb10456287f8aa822aec447fbaa

test:
  secret_key_base: d625762809f4c6b03037b4808af00d515c9b8eac0d317e67ef211f0582a9c2196a941fecd0b292ac2af4097808ad2df8689791dd28626fdaf60bedfdcd6b0ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
